### ISSUE TITLE
Ardour crashing on connect

### ISSUE THREAD

**Issue by haslinger** [Studio-Link-v2/overlay-lv2#1]
First, this seams to be really an awesome upgrade for the podcasting community, so keep up the good work! I am a Ruby on Rails dev and Linux sysadmin by trade and a podcaster by passion. So I tried to install studio link standalone on two Linux machines (Ubuntu Mate 14.04), which worked fine.

I further more installed the plugin on one of these and followed the installation guide for Ardour (though I'm a noob to Ardour). Installation worked, loading the project opens the browser, setting placing the call works, but as soon as the callee confirms the popup, the caller's Ardour crashes.

There is a short error popup "Websocket closed" and then Ardour crashes with
`May 11 15:05:11 aristoteles kernel: [26601.152835] traps: ardour-4.6.0[1518] general protection ip:7f0e5ebe2790 sp:7f0e327fb690 error:0 in libbluetooth.so.3.18.10[7f0e5ebd2000+20000]`
in syslog.
Interestingly enough, the studio link browsers stay open and the network connection still seems to be established.

**Comment by haslinger** [comment]
Thought about uninstalling bluetooth alltogether (as there is no bluetooth device buildt into this machine), but there is a dependency from Ardour to libbluetooth3 - so no luck here.

**Comment by sreimers** [comment]
This is a known namespace conflict that I'm working on and should be fixed this week. Thank you for your feedback.

https://github.com/Studio-Link-v2/backend/issues/5

**Comment by haslinger** [comment]
Cool, whenever there's something to try, I would be happy to chime in.
Btw. typo above: it's Ubuntu 16.04 not 14.04.

**Comment by sreimers** [comment]
You can test this alpha version now: https://github.com/Studio-Link-v2/backend/releases/download/v16.04.0-alpha4/studio-link-plugin-linux.zip

**Comment by haslinger** [comment]
And it works! 
I am a complete Ardour-noob, so I struggled quite a bit with the routing, Alsa and my sound cards, but finally I recorded some audio. Will try with some friends over the net and report back.
